version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:14.8-stretch # ...with this image as the primary container; this is where all `steps` will run
        environment:
          DB_CONNECTION: mongodb://localhost
      - image: mongo:4.4-bionic # and this image as the secondary service container
      - image: redis:6-alpine # and this image as the 3rd service container
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: "sudo npm install -g n mocha"
      - run:
          name: update-npm
          command: "sudo n stable"
      - run:
          name: install-npm-wee
          command: cd server && npm install
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Wait for mongodb
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: export-test-result
          environment:
            NODE_ENV: test
          command: |
            cd server && npm run test
          when: always
      - store_artifacts:
          path: ./server/reports
          destination: reports
          when: always